version: "3.9"
services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements: requirements_dev.txt
    env_file:
      - .env
    volumes:
    - .:/app
    ports:
      - "8000:8000"

