FROM python:3.11-slim as requirements-stage
WORKDIR /tmp_test
RUN pip install poetry
COPY ./pyproject.toml ./poetry.lock* /tmp_test/
RUN poetry export --dev -f requirements.txt --output requirements.txt --without-hashes
FROM python:3.11-slim
WORKDIR /app
COPY --from=requirements-stage /tmp_test/requirements.txt /test/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /test/requirements.txt
COPY ./app /app/app
COPY ./tests /app/tests
