version: "3.9"
services:
  webhook:
    build: .
    environment:
      - PYTHONPATH=.
    env_file:
      - .env
    volumes:
    - .:/app
    ports:
      - "8000:8000"
    command: sh local_dev.sh

