import logging
import os

LOG_LEVEL = int(os.getenv('LOG_LEVEL', logging.INFO))
LOCAL_MODEL_LOCATION = os.environ['LOCAL_MODEL_LOCATION']
REMOTE_MODEL_LOCATION = os.environ['REMOTE_MODEL_LOCATION']
MONGO_URL = os.environ['MONGO_URL']

DATABASE_NAME = 'recisnap'
FIREBASE_STORAGE_BASE_URL = os.environ['FIREBASE_STORAGE_BASE_URL']
GEOREF_STORAGE_BASE_URL = os.environ['GEOREF_STORAGE_BASE_URL']
DEFAULT_MODEL = 'tensor_simplificado'
